apiVersion: apps/v1 # The version of the Kubernetes API being used for apps
kind: Deployment # The type of Kubernetes object being created, in this case, a Deployment
metadata:
  name: web-workload-deployment # The name of the Deployment
  labels:
    name: web-workload-deployment # Labels to identify the Deployment
spec:
  replicas: 5 # The number of desired Pod replicas
  revisionHistoryLimit: 5 # The number of old ReplicaSets to retain to allow rollback
  strategy:
    type: RollingUpdate # The type of update strategy for the Deployment
    rollingUpdate:
      maxSurge: 1 # The maximum number of Pods that can be created above the desired number of Pods during an update
      maxUnavailable: 4 # The maximum number of Pods that can be unavailable during the update process
  selector:
    matchLabels:
      name: web-workload-deployment # Label selector for Pods; only Pods with this label will be managed by the Deployment
  template:
    metadata:
      labels:
        name: web-workload-deployment # Labels to apply to the Pods created by the Deployment
    spec:
      containers:
      - name: docker-run-app # The name of the container within the Pod
        image: docker-run-app:v1 # The Docker image to be used for this container
        resources:
          limits:
            cpu: "500m" # The maximum amount of CPU the container can use (500 millicores)
            memory: "128Mi" # The maximum amount of memory the container can use (128 MiB)
        ports:
          - containerPort: 5000 # The port that the container exposes
