apiVersion: batch/v1
kind: Job
metadata:
  name: web-workload-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello from the job"]
      restartPolicy: Never
  backoffLimit: 4
