apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-workload-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello from the cronjob"]
          restartPolicy: Never

