version: '1.0'

services:
  web:
    image: docker-run-app:v1
    build: .
    ports:
      - 5000:5000/tcp
    volumes:
      - docker-run-app-volume:/app/data
volumes:
  docker-run-app-volume:
    external: true