apiVersion: v1 # The version of the Kubernetes API being used
kind: Secret # The type of Kubernetes object being created, in this case, a Secret
metadata:
  name: web-secret # The name of the Secret
type: Opaque # The type of Secret, which means it contains arbitrary user-defined data
data:
  # base64 encoded | https://www.base64encode.org/ | https://www.base64decode.org/
  username: c29tZV91c2VybmFtZQ== # The base64 encoded value of the username
  password: c29tZV9wYXNzd29yZA== # The base64 encoded value of the password
