apiVersion: v1 # The version of the Kubernetes API being used
kind: ConfigMap # The type of Kubernetes object being created, in this case, a ConfigMap
metadata:
  name: web-configuration-configmap-propertylike # The name of the ConfigMap
data: 
  name: "Peter" # The first name of the user
  lastname: "Novac" # The last name of the user
  birthdate: "10.05.1980" # The birthdate of the user
