apiVersion: v1
kind: Pod
metadata:
  name: web-app-configmap-filelike
spec:
  containers:
    - name: docker-app-busybox
      image: busybox
      command: ["sh", "-c", "cd config; cat web-app.properties;"]
      resources:
        limits:
          cpu: "200m"
          memory: "128Mi"
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: web-configuration-configmap-filelike
      items:
      - key: "web-app.properties"
        path: "web-app.properties"
