apiVersion: v1 # The version of the Kubernetes API being used
kind: Service # The type of Kubernetes object being created, in this case, a Service
metadata:
  name: web-service-cluster-ip # The name of the Service
spec:
  ports:
  - port: 80 # The port that the Service will expose
    targetPort: 5000 # The port on the Pod that the Service should forward traffic to
    protocol: TCP # The protocol used for the Service (default is TCP)
  selector: 
    name: web-app-for-services # A label selector to identify the Pods that this Service should route traffic to
