##### FROM #####
# Docker file must start with a FROM instruction. Only ARG can be before this. 
# FROM keyword initialize a new build stage and sets the base image. 
# In this case the base image is python in 3.12-slim version
FROM python:3.12-slim AS PYTHON
