apiVersion: v1
kind: Service
metadata:
  name: web-service-node-port
spec:
  type: NodePort
  selector: 
    name: web-app-for-volumes
  ports: 
  - nodePort: 32410
    port: 80
    targetPort: 5000
    protocol: TCP
