apiVersion: v1 # The version of the Kubernetes API being used
kind: PersistentVolume # The type of Kubernetes object being created, in this case, a PersistentVolume
metadata:
  name: web-app-volume # The name of the PersistentVolume
  labels:
    name: web-app-volume # Labels to categorize and organize the PersistentVolume
spec:
  storageClassName: ssd # The StorageClass that defines the type of storage to use
  capacity:
    storage: 10Mi # The total amount of storage provided by this volume (10 MiB)
  volumeMode: Filesystem # The type of volume, in this case, a filesystem
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain # The policy to retain the volume when the claim is deleted
  hostPath:
    path: "/app/data/" # The path on the host node's filesystem to expose to the Pod
