apiVersion: v1 # The version of the Kubernetes API being used
kind: PersistentVolumeClaim # The type of Kubernetes object being created, in this case, a PersistentVolumeClaim
metadata:
  name: web-app-volume-claim # The name of the PersistentVolumeClaim
spec:
  accessModes: 
    - ReadWriteOnce # The volume can be mounted as read-write by a single node
  resources: 
    requests: 
      storage: 5Mi # The amount of storage requested for the volume (5 MiB)
  storageClassName: ssd # The StorageClass that defines the type of storage to use
  selector: 
    matchLabels: 
      name: web-app-volume # A label selector to match a specific PersistentVolume