apiVersion: v1
kind: Pod
metadata:
  name: web-app-with-liveness
  labels:
    name: web-app-with-liveness
spec:
  containers:
  - name: docker-run-app
    image: docker-run-app:v1
    ports:
    - containerPort: 5000
    resources:
      limits:
        cpu: "700m"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /read
        port: 5000
        httpHeaders:
        - name: Custom-Header
          value: HelloThere
      initialDelaySeconds: 5
      periodSeconds: 10
