apiVersion: v1
kind: Pod
metadata:
  name: web-app-with-resources
  labels:
    name: web-app-with-resources
spec:
  containers:
  - name: docker-run-app
    image: docker-run-app:v1
    ports:
    - containerPort: 5000
    resources:
      limits:
        cpu: "700m"
        memory: "256Mi"
