apiVersion: v1 # The version of the Kubernetes API being used
kind: Pod # The type of Kubernetes object being created, in this case, a Pod
metadata: 
  name: web-app-with-liveness # The name of the Pod
  labels: 
    name: web-app-with-liveness # Labels to categorize and organize the Pod
spec: 
  containers: 
  - name: docker-run-app # The name of the container within the Pod
    image: docker-run-app:v1 # The Docker image to be used for this container
    ports: 
    - containerPort: 5000 # The port that the container exposes
    resources: 
      limits: 
        cpu: "700m" # The maximum amount of CPU the container can use (700 millicores)
        memory: "256Mi" # The maximum amount of memory the container can use (256 MiB)
    livenessProbe: # Configuration for the liveness probe, which checks if the container is running
      httpGet: 
        path: /read # The HTTP path to check for the liveness probe
        port: 5000 # The port to use for the liveness probe
        httpHeaders: 
        - name: Custom-Header # Custom HTTP header name to include in the probe request
          value: HelloThere # Value for the custom HTTP header
      initialDelaySeconds: 5 # Time to wait before performing the first probe (in seconds)
      periodSeconds: 10 # Frequency of performing the probe (in seconds)

