apiVersion: v1 # The version of the Kubernetes API being used
kind: Pod # The type of Kubernetes object being created, in this case, a Pod
metadata:
  name: web-app-with-init-container # The name of the Pod
  labels:
    name: web-app-with-init-container # Labels to categorize and organize the Pod
spec:
  initContainers: # Containers that run before the main containers, typically used for initialization tasks
  - name: init-my-container # The name of the init container
    image: busybox # The Docker image to be used for this init container
    command: ["sh", "-c", "echo Initializing..."] # Command to run in the init container
    securityContext:
      runAsUser: 0 # The user ID to run the init container as (root user)
  containers:
  - name: docker-run-app # The name of the container within the Pod
    image: docker-run-app:v1 # The Docker image to be used for this container
    ports:
    - containerPort: 5000 # The port that the container exposes